/Users/user/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
[0m05:44:31  Running with dbt=1.9.4
[0m05:44:32  Registered adapter: postgres=1.9.0
[0m05:44:32  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.ecommerce_test.sources
[0m05:44:32  Found 7 models, 25 data tests, 4 sources, 810 macros
[0m05:44:32  
[0m05:44:32  Concurrency: 4 threads (target='dev')
[0m05:44:32  
[0m05:44:32  Building catalog
[0m05:44:32  Catalog written to /Users/user/Desktop/Data-Engineering/Day12/Ex2/ecommerce_dbt/target/catalog.json
